env: "development"
api_gateway:
    host: "localhost"
    port: 3000
    address: "localhost:3000"
schedule_service:
    host: "localhost"
    port: 3006
    address: "localhost:3006"
secret: "$ecr3t"
db:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "0000"
  dbname: "crm-scheduleService"