env: "development"
client:
    host: "localhost"
    port: 5173
    address: "http://localhost:5173"
api_gateway:
    host: "localhost"
    port: 3000
    address: "localhost:3000"
auth_service:
    host: "localhost"
    port: 3001
    address: "localhost:3001"