env: "development"
api_gateway:
    host: "localhost"
    port: 3000
    address: "localhost:3000"
users_service:
    host: "localhost"
    port: 3002
    address: "localhost:3002"
db:
    host: "localhost"
    port: 5432
    user: "postgres"
    password: "0000"
    dbname: "crm-usersService"