env: "local"
client:
    protocol: "https"
    host: "45.156.23.236"
    port: 5173
    address: "https://crm-fitness.ru"
api_gateway:
    protocol: "https"
    host: "45.156.23.236"
    port: 3000
    address: "https://dev.crm-fitness:3000"
auth_service:
    protocol: "https"
    host: "45.156.23.236"
    port: 3001
    address: "https://45.156.23.236:3001"