--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2
-- Dumped by pg_dump version 16.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE IF EXISTS "crm-authService";
--
-- Name: crm-authService; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE "crm-authService" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'Russian_Russia.1251';


ALTER DATABASE "crm-authService" OWNER TO postgres;

\connect -reuse-previous=on "dbname='crm-authService'"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts (
    id integer NOT NULL,
    login character varying NOT NULL,
    password character varying NOT NULL,
    last_activity timestamp without time zone,
    date_created timestamp without time zone
);


ALTER TABLE public.accounts OWNER TO postgres;

--
-- Name: sessions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sessions (
    id integer NOT NULL,
    id_account integer,
    access_token character varying,
    date_expiration_access_token timestamp without time zone,
    refresh_token character varying,
    date_expiration_refresh_token timestamp without time zone
);


ALTER TABLE public.sessions OWNER TO postgres;

--
-- Name: sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.users_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.users_id_seq OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.accounts.id;


--
-- Name: accounts id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- Data for Name: accounts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts (id, login, password, last_activity, date_created) FROM stdin;
67	333	3d9811cb89f6961e0f3a65d73785fa682284582842754dc7f1554fbdb1a701c5	2024-06-11 00:26:58.989978	2024-06-06 23:09:09.129363
65	555	a217099448fbcbe0386d5167803eaae8c938c0ca921cada9a7b8a0f8547f0682	2024-06-11 00:28:09.595482	2024-06-05 14:42:05.763031
64	666	687e31da4e79db2bf0b7ae88b60f5fea0ddec3079ccebf1e39d91951fffc6606	2024-06-11 00:31:13.495484	2024-06-05 14:40:03.117513
61	321	d9b23136ec5a38bc8714537d82358a2f5c406e56a616fdc941231bd27b24d68c	2024-06-11 01:55:39.524977	2024-05-30 09:33:47.588416
63	777	4e5342de9fe02f90ce045fe536e1c47f937108079b1a64cda0039153422d7b1d	2024-06-09 19:14:51.785899	2024-06-05 13:44:39.390543
54	123	d13e40a29eb822914e3dc8098d3d1b05bf8fe1c602e3d021cd9ae73b18216582	2024-06-11 02:25:51.892156	2024-05-27 19:18:20.819001
\.


--
-- Data for Name: sessions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.sessions (id, id_account, access_token, date_expiration_access_token, refresh_token, date_expiration_refresh_token) FROM stdin;
724	54	fcd8a310a789d46f13eead8b05952ead872b0b9f52b94767103265e0690ce748	2024-06-11 02:26:06.601746	00bfb549bf5030833c3c77de9b31da8ea7e9c6f92d3c2828255f3ab59c5e1b63	2024-06-11 02:26:37.719772
706	64	c23c4bb474cc23085fe8e6c99646a228252142448e6c51e251aabdbfd563e644	2024-06-11 00:31:30.088164	2c0783516ad154cc109dd559e9764bd6195f5b31ae32f8888fa7d493742043fc	2024-06-11 00:33:14.49398
719	61	5df2ef07f1433b2a8dd58179d2ea2385e2826402b3bc7131ae771fcfdc71e7a9	2024-06-11 01:56:01.921957	e3f85685c855b117e118a011cc6399e360c11d31c25e27cb17afec7b2076e3cc	2024-06-11 01:56:06.789743
\.


--
-- Name: sessions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.sessions_id_seq', 724, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 70, true);


--
-- Name: sessions sessions_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_pk PRIMARY KEY (id);


--
-- Name: accounts users_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT users_pk UNIQUE (login);


--
-- Name: accounts users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: sessions sessions_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_users_id_fk FOREIGN KEY (id_account) REFERENCES public.accounts(id);


--
-- PostgreSQL database dump complete
--

