--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2
-- Dumped by pg_dump version 16.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE IF EXISTS "crm-authService";
--
-- Name: crm-authService; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE "crm-authService" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'Russian_Russia.1251';


ALTER DATABASE "crm-authService" OWNER TO postgres;

\connect -reuse-previous=on "dbname='crm-authService'"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts (
    id integer NOT NULL,
    login character varying NOT NULL,
    password character varying NOT NULL,
    last_activity timestamp without time zone,
    date_created timestamp without time zone
);


ALTER TABLE public.accounts OWNER TO postgres;

--
-- Name: sessions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sessions (
    id integer NOT NULL,
    id_account integer,
    access_token character varying,
    date_expiration_access_token timestamp without time zone,
    refresh_token character varying,
    date_expiration_refresh_token timestamp without time zone
);


ALTER TABLE public.sessions OWNER TO postgres;

--
-- Name: sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.users_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.users_id_seq OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.accounts.id;


--
-- Name: accounts id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- Data for Name: accounts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts (id, login, password, last_activity, date_created) FROM stdin;
54	123	d13e40a29eb822914e3dc8098d3d1b05bf8fe1c602e3d021cd9ae73b18216582	2024-06-30 18:03:01.884865	2024-05-27 19:18:20.819001
75	888	7f4119837c6c90072eb38ef4c99cd1ac52f5f7e53a9cc4c65565899639986bff	2024-06-30 18:03:53.669602	2024-06-29 20:19:16.770218
67	333	3d9811cb89f6961e0f3a65d73785fa682284582842754dc7f1554fbdb1a701c5	2024-06-11 12:30:53.580132	2024-06-06 23:09:09.129363
65	555	a217099448fbcbe0386d5167803eaae8c938c0ca921cada9a7b8a0f8547f0682	2024-06-16 19:34:39.385261	2024-06-05 14:42:05.763031
76	999	9b18c060b88095a6c08094ef6eda37ce7d87c40b6e8f72b42549e581a1c831fb	2024-06-29 20:22:23.434172	2024-06-29 20:22:23.434172
63	777	4e5342de9fe02f90ce045fe536e1c47f937108079b1a64cda0039153422d7b1d	2024-06-16 14:55:53.033999	2024-06-05 13:44:39.390543
61	321	d9b23136ec5a38bc8714537d82358a2f5c406e56a616fdc941231bd27b24d68c	2024-06-30 17:58:36.384	2024-05-30 09:33:47.588416
64	666	687e31da4e79db2bf0b7ae88b60f5fea0ddec3079ccebf1e39d91951fffc6606	2024-06-30 17:58:45.653378	2024-06-05 14:40:03.117513
\.


--
-- Data for Name: sessions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.sessions (id, id_account, access_token, date_expiration_access_token, refresh_token, date_expiration_refresh_token) FROM stdin;
820	76	5a66a5f84d356a2454442b874eef943a22d85e61a8b6025dc2542459df99537f	2024-06-29 20:52:23.434172	14a0b2039432444b2067a9538296aa7b54e9f215b2366b4c63c5bb2ae6368b29	2024-07-29 20:22:23.434172
828	61	9e4dbf64fe65a9609b149f14a05f999967bb36dac8aaff2a8ff0b17486f457c7	2024-06-30 18:28:36.384777	64005399a256770d1a7a609f26d5bc3fa8fa22364f6a06303b121b73a57da4e4	2024-07-30 17:58:36.384777
829	64	c1d180d8e6d7c3c7780b0b9adb5c9315cf0105ab93d6bfbea63c39c716a9b34e	2024-06-30 18:28:45.653905	0caa471ec7b6971e05c50c05481faded431cee6dc398bf2cadf315bf94de2298	2024-07-30 17:58:45.654442
830	54	328f5d73a48b9acba1e3103933fef7876c47ac86e3f6a33837818b97383ee5f1	2024-06-30 18:33:01.885403	d61452003d046b610e33cb6ac06a98e0fc9a6160918b2c9d167df0ca36da1174	2024-07-30 18:03:01.885403
831	75	00dd2c51ab9028f394a279a8f045c47a83ef43be7fd34f399edc9fb1b14ec9fe	2024-06-30 18:33:53.670135	14898395428c62c1469c6c1c4fee4cadd5eac15748eb4a09a1bd6a2205babb5f	2024-07-30 18:03:53.670135
794	63	d40da01d45a74bc0b5d5d742d6288f32a84f085144944a344be9f683619fd3cd	2024-06-16 15:25:51.595776	1cb48947d9b3c0ebac1bcd36c8b935421d37d63fb64cc00e4013a0e268dcdb28	2024-07-16 14:55:51.595776
810	65	d81c4f4feaa784828f668122c191dab0676529db5c7ffa99a7778a07e18856a1	2024-06-16 20:04:39.38635	d261c25769e2a28e934da4daed5c033b563809019ee0cd108ec9a4a803b9120d	2024-07-16 19:34:39.38635
\.


--
-- Name: sessions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.sessions_id_seq', 831, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 76, true);


--
-- Name: sessions sessions_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_pk PRIMARY KEY (id);


--
-- Name: accounts users_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT users_pk UNIQUE (login);


--
-- Name: accounts users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: sessions sessions_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_users_id_fk FOREIGN KEY (id_account) REFERENCES public.accounts(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

