env: "production"
api_gateway:
    host: "193.169.105.90"
    port: 3000
    address: "193.169.105.90:3000"
storage_service:
    host: "193.169.105.90"
    port: 3003
    address: "193.169.105.90:3003"
db:
    host: "193.169.105.90"
    port: 5432
    user: "postgres"
    password: "0000"
    dbname: "crm-storageService"