env: "production"
api_gateway:
    host: "api-gateway"
    port: 3000
    address: "api-gateway:3000"
subs_service:
    host: "0.0.0.0"
    port: 3004
    address: "0.0.0.0:3004"
db:
    host: "172.17.0.1"
    port: 5432
    user: "postgres"
    password: "0000"
    dbname: "crm-subsService"