--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2
-- Dumped by pg_dump version 16.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE IF EXISTS "crm-authService";
--
-- Name: crm-authService; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE "crm-authService" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'Russian_Russia.1251';


ALTER DATABASE "crm-authService" OWNER TO postgres;

\connect -reuse-previous=on "dbname='crm-authService'"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: sessions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sessions (
    id integer NOT NULL,
    id_user integer,
    access_token character varying,
    date_expiration_access_token timestamp without time zone,
    refresh_token character varying,
    date_expiration_refresh_token timestamp without time zone
);


ALTER TABLE public.sessions OWNER TO postgres;

--
-- Name: sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id integer NOT NULL,
    login character varying NOT NULL,
    password character varying NOT NULL,
    name character varying,
    surname character varying,
    patronymic character varying,
    role integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.users_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.users_id_seq OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;


--
-- Name: users id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- Data for Name: sessions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.sessions (id, id_user, access_token, date_expiration_access_token, refresh_token, date_expiration_refresh_token) FROM stdin;
81	45	c78e4006aee923d287bc9180a319cd1f60d5e66578ec96da2c742b69814e709b	2024-05-19 10:39:37.063949	7c8150fe96c96b4365950ff7f14411bbbd677a8724c0eeed2cd592637bb7c528	2024-05-19 10:43:37.063949
10	35	6552ecca9c8742e9ad2e7594ca67d87ff940fd92c56c5bc6114754346054aa75	2024-05-12 17:23:00	b1f288e7f995761c3aa92ed3392793d80c1e42797b365d7c0d87d93ddc87a7db	2024-05-12 17:28:31.199679
199	18	63e73e328d37d2f831054fda6c3b5c15931e25024065f7a33d0fe330273360d5	2024-05-22 13:24:44.647721	7213ef3022bba7a3483f07eb059b7ced2eb3ab60f416e4f74f3bf1161d8aba5d	2024-05-22 13:28:44.647721
71	21	cc07c67b1463206aac209f7796c85e8b744c61d1975881f28c42b5545ebe224f	2024-05-18 20:47:41.301229	d654eac2e31d4124da52021b8d3f534e9e83c530b0ed345f3cb9481a8ed8a9cb	2024-05-18 20:51:41.301229
74	27	89ddb46ab1d11f66bee0cdd01d1fce82760f9f2891beaefc2c525acb21dc5d6f	2024-05-18 20:49:27.81892	95de7045ca5342c2dab8a8f2a56c8c92b3f5a8b847278528d422b626ff8e67eb	2024-05-18 20:53:27.81892
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, login, password, name, surname, patronymic, role) FROM stdin;
18	123	d13e40a29eb822914e3dc8098d3d1b05bf8fe1c602e3d021cd9ae73b18216582	\N	\N	\N	0
21	1234	d13e40a29eb822914e3dc8098d3d1b05bf8fe1c602e3d021cd9ae73b18216582	\N	\N	\N	0
22	12345	d13e40a29eb822914e3dc8098d3d1b05bf8fe1c602e3d021cd9ae73b18216582	\N	\N	\N	0
23	123456	d13e40a29eb822914e3dc8098d3d1b05bf8fe1c602e3d021cd9ae73b18216582	\N	\N	\N	0
24	asdasd	10291d744512a7e669b80e18ae4a243a5e7b6c5ec4f728cdd519e4212d514732	\N	\N	\N	0
26		10291d744512a7e669b80e18ae4a243a5e7b6c5ec4f728cdd519e4212d514732	\N	\N	\N	0
27	1234567	d13e40a29eb822914e3dc8098d3d1b05bf8fe1c602e3d021cd9ae73b18216582	\N	\N	\N	0
28	12345678	d13e40a29eb822914e3dc8098d3d1b05bf8fe1c602e3d021cd9ae73b18216582	\N	\N	\N	0
29	123456789	d13e40a29eb822914e3dc8098d3d1b05bf8fe1c602e3d021cd9ae73b18216582	\N	\N	\N	0
30	1234567891	d13e40a29eb822914e3dc8098d3d1b05bf8fe1c602e3d021cd9ae73b18216582	\N	\N	\N	0
31	12345678912	d13e40a29eb822914e3dc8098d3d1b05bf8fe1c602e3d021cd9ae73b18216582	\N	\N	\N	0
32	123456789123	d13e40a29eb822914e3dc8098d3d1b05bf8fe1c602e3d021cd9ae73b18216582	\N	\N	\N	0
33	1234567891234	d13e40a29eb822914e3dc8098d3d1b05bf8fe1c602e3d021cd9ae73b18216582	\N	\N	\N	0
34	12345678912345	d13e40a29eb822914e3dc8098d3d1b05bf8fe1c602e3d021cd9ae73b18216582	\N	\N	\N	0
35	123456789123456	d13e40a29eb822914e3dc8098d3d1b05bf8fe1c602e3d021cd9ae73b18216582	\N	\N	\N	0
36	1234567891234567	d13e40a29eb822914e3dc8098d3d1b05bf8fe1c602e3d021cd9ae73b18216582	\N	\N	\N	0
37	12345678912345678	d13e40a29eb822914e3dc8098d3d1b05bf8fe1c602e3d021cd9ae73b18216582	\N	\N	\N	0
38	123456789123456789	d13e40a29eb822914e3dc8098d3d1b05bf8fe1c602e3d021cd9ae73b18216582	\N	\N	\N	0
40	12377	d13e40a29eb822914e3dc8098d3d1b05bf8fe1c602e3d021cd9ae73b18216582	\N	\N	\N	0
42	123778	d13e40a29eb822914e3dc8098d3d1b05bf8fe1c602e3d021cd9ae73b18216582	\N	\N	\N	0
43	333	d13e40a29eb822914e3dc8098d3d1b05bf8fe1c602e3d021cd9ae73b18216582	\N	\N	\N	0
44	444	6b120b0eeb129d31c0fb2a64828331c664394c8d89c6287ebb5e131294e19b85	\N	\N	\N	0
45	555	a217099448fbcbe0386d5167803eaae8c938c0ca921cada9a7b8a0f8547f0682	\N	\N	\N	0
47	666	687e31da4e79db2bf0b7ae88b60f5fea0ddec3079ccebf1e39d91951fffc6606	\N	\N	\N	0
\.


--
-- Name: sessions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.sessions_id_seq', 199, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 52, true);


--
-- Name: sessions sessions_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_pk PRIMARY KEY (id);


--
-- Name: users users_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pk UNIQUE (login);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: sessions sessions_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_users_id_fk FOREIGN KEY (id_user) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

