env: "development"
api_gateway:
    host: "localhost"
    port: 3000
    address: "localhost:3000"
training_service:
    host: "localhost"
    port: 3005
    address: "localhost:3005"
db:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "0000"
  dbname: "crm-trainingService"