env: "development"
api_gateway:
    host: "localhost"
    port: 3000
    address: "localhost:3000"
storage_service:
    host: "localhost"
    port: 3003
    address: "localhost:3003"
db:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "0000"
  dbname: "crm-storageService"