env: "local"
api_gateway:
    host: "localhost"
    port: 3000
    address: "localhost:3000"
auth_service:
    host: "localhost"
    port: 3001
    address: "localhost:3001"
secret: "$ecr3t"
db:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "0000"
  dbname: "crm-authService"