env: "production"
api_gateway:
    host: "api-gateway"
    port: 3000
    address: "api-gateway:3000"
auth_service:
    host: "0.0.0.0"
    port: 3001
    address: "0.0.0.0:3001"
secret: "$ecr3t"
db:
    host: "172.17.0.1"
    port: 5432
    user: "postgres"
    password: "0000"
    dbname: "crm-authService"
redis:
    host: "172.17.0.1"
    port: 6379
    password: "0000"
    address: "172.17.0.1:6379"